spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #Postgresql properties
  datasource:
    url: jdbc:postgresql://192.168.1.31:5432/postgres
    username: amigoscode
    password: password
    driver-class-name: org.postgresql.Driver
  #JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

